# Security & JWT 설정 파일
# Spring Boot Profile: security

# 공통 보안 설정
security:
  public-urls:
    - "/api-docs"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/api/join/**"
    - "/api/auth/login"

# 공통 JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY:your_jwt_secret_key_at_least_32_characters}
  access-token:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}  # 1시간 (밀리초)